[package]
name = "dcode"
version = "0.1.0"
authors = ["Igor <ig.evg.po@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
ferris-says="0.1"